# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_components/salutespeech/api/grpc/synthesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7custom_components/salutespeech/api/grpc/synthesis.proto\x12\x18smartspeech.synthesis.v1\x1a\x1egoogle/protobuf/duration.proto\"\xee\x02\n\x10SynthesisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12P\n\x0e\x61udio_encoding\x18\x02 \x01(\x0e\x32\x38.smartspeech.synthesis.v1.SynthesisRequest.AudioEncoding\x12\x10\n\x08language\x18\x03 \x01(\t\x12L\n\x0c\x63ontent_type\x18\x04 \x01(\x0e\x32\x36.smartspeech.synthesis.v1.SynthesisRequest.ContentType\x12\r\n\x05voice\x18\x05 \x01(\t\x12\x15\n\rrebuild_cache\x18\x06 \x01(\x08\"Q\n\rAudioEncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\r\n\tPCM_S16LE\x10\x01\x12\x08\n\x04OPUS\x10\x02\x12\x07\n\x03WAV\x10\x03\"!\n\x0b\x43ontentType\x12\x08\n\x04TEXT\x10\x00\x12\x08\n\x04SSML\x10\x01\"T\n\x11SynthesisResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x31\n\x0e\x61udio_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration2v\n\x0bSmartSpeech\x12g\n\nSynthesize\x12*.smartspeech.synthesis.v1.SynthesisRequest\x1a+.smartspeech.synthesis.v1.SynthesisResponse0\x01\x42\x13\n\x04TODOZ\x0b./;protocolb\x06proto3')



_SYNTHESISREQUEST = DESCRIPTOR.message_types_by_name['SynthesisRequest']
_SYNTHESISRESPONSE = DESCRIPTOR.message_types_by_name['SynthesisResponse']
_SYNTHESISREQUEST_AUDIOENCODING = _SYNTHESISREQUEST.enum_types_by_name['AudioEncoding']
_SYNTHESISREQUEST_CONTENTTYPE = _SYNTHESISREQUEST.enum_types_by_name['ContentType']
SynthesisRequest = _reflection.GeneratedProtocolMessageType('SynthesisRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHESISREQUEST,
  '__module__' : 'custom_components.salutespeech.api.grpc.synthesis_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.synthesis.v1.SynthesisRequest)
  })
_sym_db.RegisterMessage(SynthesisRequest)

SynthesisResponse = _reflection.GeneratedProtocolMessageType('SynthesisResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHESISRESPONSE,
  '__module__' : 'custom_components.salutespeech.api.grpc.synthesis_pb2'
  # @@protoc_insertion_point(class_scope:smartspeech.synthesis.v1.SynthesisResponse)
  })
_sym_db.RegisterMessage(SynthesisResponse)

_SMARTSPEECH = DESCRIPTOR.services_by_name['SmartSpeech']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\004TODOZ\013./;protocol'
  _SYNTHESISREQUEST._serialized_start=118
  _SYNTHESISREQUEST._serialized_end=484
  _SYNTHESISREQUEST_AUDIOENCODING._serialized_start=368
  _SYNTHESISREQUEST_AUDIOENCODING._serialized_end=449
  _SYNTHESISREQUEST_CONTENTTYPE._serialized_start=451
  _SYNTHESISREQUEST_CONTENTTYPE._serialized_end=484
  _SYNTHESISRESPONSE._serialized_start=486
  _SYNTHESISRESPONSE._serialized_end=570
  _SMARTSPEECH._serialized_start=572
  _SMARTSPEECH._serialized_end=690
# @@protoc_insertion_point(module_scope)
